export const districts=["Narsingdi Sadar",
"Palash",
"Belabo",
"Monohardi",
"Raipura",
"Shibpur",
"Ayubpur",
"Baghaba",
"Chakradha",
"Dulalpur",
"Joshor",
"Joynagar",
"Machhimpur",
"Putia",
"Sadharchar",
"Char Sindur",
"Danga",
"Gazaria",
"Jinardi",
"Alokbali",
"Amdia",
"Chardighaldi",
"Chinishpur",
"Hajipur",
"Karimpur",
"Kathalia",
"Nuralapur",
"Mahishasura",
"Meherpara",
"Nazarpur",
"Poikarchar",
"Panchdona",
"Silmandi",
" Adiabad",
"Alipura",
"Amirganj",
"Banshgari",
"Chanderkandi",
"Chanpur",
"Char Aralia",
"Charmadhua",
"Charsubuddi",
"Dowkarchar",
"Hairmara",
"Maheshpur",
"Marjal",
"Mirzanagar",
"Mirzapur",
"Mirzarchar",
" Musapur",
"Nilakhya",
"Palashtali",
"Paratali",
"Radhanagar",
"Roypura",
"Sreenagar",
"Uttarbakharnagar",
"Amlaba",
"Bajnabo",
"Belabo",
"Binnabaid",
"Narayanpur",
"Patuli",
"Sallabad",
"Charujilab",
"Barachapa",
"Chalakchar",
"Chandanbari",
"Charmandalia",
"Daulatpur",
"Akduaria",
"Gotashia",
"Kanchikata",
"Khidirpur",
"Lebutala",
"Shukundi"]
export const bloodType=['A+','A-','B+','B-','O+','O-','AB+','AB-']
export const turnIntoSelectFormat=(data)=> {
    return data.map(d => ({
        "value": d,
        "label": d.charAt(0).toUpperCase() + d.slice(1)
    }))
}